name: PSC Driver

on: [push, pull_request, workflow_dispatch]

env:
  SETUP_PATH: .ci-local
  CMP: gcc

jobs:
  build-linux:
    name: ${{ matrix.configuration }} / ${{ matrix.os }} / ${{ matrix.base }}
    runs-on: ${{ matrix.os }}
    # Set environment variables from matrix parameters
    env:
      BCFG: ${{ matrix.configuration }}
      BASE: ${{ matrix.base }}
      EXTRA: ${{ matrix.extra }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            extra: ""
            configuration: static
            base: "7.0"

          - os: ubuntu-latest
            extra: "CMD_CXXFLAGS=-std=c++11 -Wall -Werror"
            configuration: default
            base: "7.0"

          - os: macos-latest
            configuration: default
            base: "7.0"

          - os: ubuntu-latest
            extra: ""
            configuration: default
            base: "3.15"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Apt
      if: runner.os == 'Linux'
      run: sudo apt-get -y install libevent-dev

    - name: Brew
      if: runner.os == 'macOS'
      run: |
        brew config
        brew install libevent
        brew info libevent
        ls /opt/homebrew/include/event2/event.h
        echo "CPATH=/opt/homebrew/include" >> $GITHUB_ENV
        echo "LIBRARY_PATH=/opt/homebrew/lib" >> $GITHUB_ENV

    - name: Prepare and compile dependencies
      run: python .ci/cue.py prepare

    - name: Build main module
      run: python .ci/cue.py build

    - name: Run main module tests
      run: python .ci/cue.py test

    - name: Collect and show test results
      if: always()
      run: python .ci/cue.py test-results
